### PR TITLE
Add new CSV file example

### PR DESCRIPTION
**Pull request by sbesson**
This PR:
- includes a level 2 CSV file generated by Philippe
- migrates the example description to a top-level Readme file

/cc @simleo

### CODE REVIEW

**Comment by simleo** [comment]
Why are Z indices floats?

**Comment by simleo** [comment]
Do we have image data for this?

**Comment by proudot** [comment]
The detection is done only at the pixel level, not sub pixel data. However the z coordinatesjj are normalized to the lateral pixel size.

This is unpublished 3D images of the  mitosic spindle. I should probably re do it with sub pixellic localization in a previously published data set. That should be quick.

Thanks for the input. -- Philippe

**Comment by sbesson** [comment]
Closing in favor of new repository (CMSO-Samples)

**Pull request closed without merging**
